# -*- coding: utf-8 -*-
"""
Created on Mon Mar 07 14:49:50 2016

@author: amjadmk
"""

import os
import shutil

rensSATIndia2009 = [
    ["Cultivation_1.Plot-Info","Cult1_PlotInfo"],
    ["Cultivation_2.Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_3.Cult_ip_AP","Cult3_ipAP"],
    ["Cultivation_3.Cult_ip_GJ","Cult3_ipGJ"],
    ["Cultivation_3.Cult_ip_KN","Cult3_ipKN"],
    ["Cultivation_3.Cult_ip_MH","Cult3_ipMH"],
    ["Cultivation_3.Cult_ip_MP","Cult3_ipMP"],
    ["Employment_1.K_gen_info","Emp1_GenInfo"],
    ["Employment_2.Employment","Emp1_Emp"],
    ["GES_A.Household_details","GesA_HHDetails"],
    ["GES_B.Landholding_details","GesB_Landholding"],
    ["GES_C.Livestock_inv","GesC_Livestock"],
    ["GES_D.Farm_equipment","GesD_FarmEquip"],
    ["GES_E.Building","GesE_Building"],
    ["GES_E.Con_durables","GesE_ConDurables"],
    ["GES_E.Other_durables","GesE_OtherDurables"],
    ["GES_F.Stock_inv","GesF_StockInv"],
    ["GES_G.Debt_credit","GesG_FinAssLia"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_I.1.Gend_decision_making","GesI1_GendDM"],
    ["GES_I.2.Gend_crop_cult","GesI2_GendCult"],
    ["GES_J.1.Mart_info","GesJ1_MktInfo"],
    ["GES_J.2.Info_ranking","GesJ2_InfoRank"],
    ["GES_J.3.Info_facility_rating","GesJ3_InfoFacilityRating"],
    ["GES_K.1_2.Coping_Mech","GesK12_CopingMech"],
    ["GES_K.3.Govt_assistance","GesK3_DroughAssist"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["Livestock_Z_gen_info","LS_GenInfo"],
    ["Livestock_Livestock","LS_Livestock"],
    ["MPrice_Commodities","MPrice_Commodities"],
    ["MPrice_Gen_info","MPrice_GenInfo"],
    ["MPrice_Machines","MPrice_Machines"],
    ["MPrice_Others","MPrice_Others"],
    ["MPrice_Seeds","MPrice_Seeds"],
    ["MPrice_Transport","MPrice_Transport"],
    ["MPrice_Wages","MPrice_Wages"],
    ["Plotlist_1.Gen_Info","PL1_GenInfo"],
    ["Plotlist_2.Plot_List","PL2_PlotList"],
    ["Transaction_Busi_ca_co","Trans_BusiCaCo"],
    ["Transaction_Fin_Tranwb","Trans_FinTrans"],
    ["Transaction_Food_items_AP","Trans_FoodAP"],
    ["Transaction_Food_items_GJ","Trans_FoodGJ"],
    ["Transaction_Food_items_KN","Trans_FoodKN"],
    ["Transaction_Food_items_MH","Trans_FoodMH"],
    ["Transaction_Food_items_MP","Trans_FoodMP"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_L_gen_info","Trans_GenInfo"],
    ["Transaction_Non_food_items","Trans_NF"],
    ["Transaction_Pur_Inputs_Fodder","Trans_InputsFodder"],
    ["Transaction_Prod_Sold","Trans_ProdSold"],
    ["Transaction_Sale_pur","Trans_SalePur"],
    ["HCS_1.Hcs_gen_info","HCS1_GenInfo"],
    ["HCS_2.Household_info","HCS2_HHInfo"],
    ["HCS_3.Oper_holding","HCS3_OperHolding"],
    ["HCS_4.Reso_livestock","HCS4_ResoLivestock"],
    ["HCS_5.Reso_farm_equip","HCS4_ResoFarmEquip"],
    ["HCS_6.Fam_Comp","HCS5_FamComp"]]


rensSATIndia2010 = [
    ["Cultivation_Plot-Info","Cult1_PlotInfo"],
    ["Cultivation_Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_Cult_ip_AP","Cult3_ipAP"],
    ["Cultivation_Cult_ip_GJ","Cult3_ipGJ"],
    ["Cultivation_Cult_ip_KN","Cult3_ipKN"],
    ["Cultivation_Cult_ip_MH","Cult3_ipMH"],
    ["Cultivation_Cult_ip_MP","Cult3_ipMP"],
    ["Employment_Gen_info","Emp1_GenInfo"],
    ["Employment_Employment_AP","Emp1_EmpAP"],
    ["Employment_Employment_GJ","Emp1_EmpGJ"],
    ["Employment_Employment_KN","Emp1_EmpKN"],
    ["Employment_Employment_MH","Emp1_EmpMH"],
    ["Employment_Employment_MP","Emp1_EmpMP"],
    ["GES_A.Household_details","GesA_HHDetails"],
    ["GES_B.Landholding_details","GesB_Landholding"],
    ["GES_C.Livestock_inv","GesC_Livestock"],
    ["GES_D.Farm_equipment","GesD_FarmEquip"],
    ["GES_E.Building","GesE_Building"],
    ["GES_E.Con_durables","GesE_ConDurables"],
    ["GES_E.Other_durables","GesE_OtherDurables"],
    ["GES_F.Stock_inv","GesF_StockInv"],
    ["GES_G.Debt_credit","GesG_FinAssLia"],
    ["GES_Gen_Info","Ges_GenInfo"],
    ["GES_H.1.Gend_decision_making","GesI1_GendDM"],
    ["GES_H.2.Gend_crop_cult","GesI2_GendCult"],
    ["GES_I.1.Mart_info","GesJ1_MktInfo"],
    ["GES_I.2.Info_ranking","GesJ2_InfoRank"],
    ["GES_J.1_2.Coping_Mech","GesK12_CopingMech"],
    ["GES_J.3.Govt_assistance","GesK3_DroughAssist"],
    ["GES_J.4.How_reliable","GesJ4_ReliabilityRank"],
    ["GES_J.5.Proact_measures","GesJ5_Proactivity"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["Livestock_Fod_feed-pur","LS_FoodFed"],
    ["Livestock_gen_info","LS_GenInfo"],
    ["Livestock_Livestock","LS_Livestock"],
    ["MPrice_Commodities","MPrice_Commodities"],
    ["MPrice_Gen_info","MPrice_GenInfo"],
    ["MPrice_Machines","MPrice_Machines"],
    ["MPrice_Others","MPrice_Others"],
    ["MPrice_Seeds","MPrice_Seeds"],
    ["MPrice_Transport","MPrice_Transport"],
    ["MPrice_Wages","MPrice_Wages"],
    ["Plotlist_Gen_Info","PL1_GenInfo"],
    ["Plotlist_Plot_List","PL2_PlotList"],
    ["Transaction_Ben_govt_prog","Trans_BenGovtProg"],
    ["Transaction_Fin_Tran","Trans_FinTrans"],
    ["Transaction_Food_items_AP","Trans_FoodAP"],
    ["Transaction_Food_items_GJ","Trans_FoodGJ"],
    ["Transaction_Food_items_KN","Trans_FoodKN"],
    ["Transaction_Food_items_MH","Trans_FoodMH"],
    ["Transaction_Food_items_MP","Trans_FoodMP"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_gen_info","Trans_GenInfo"],
    ["Transaction_Non_food_items","Trans_NF"],
    ["Transaction_Prod_Sold","Trans_ProdSold"],
    ["Transaction_Sale_pur","Trans_SalePur"]]


rensSATIndia2011 = [
    ["Cultivation_Plot_Info","Cult1_PlotInfo"],
    ["Cultivation_Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_Cult_ip_AP","Cult3_ipAP"],
    ["Cultivation_Cult_ip_GJ","Cult3_ipGJ"],
    ["Cultivation_Cult_ip_KN","Cult3_ipKN"],
    ["Cultivation_Cult_ip_MH","Cult3_ipMH"],
    ["Cultivation_Cult_ip_MP","Cult3_ipMP"],
    ["Employment_Gen_info","Emp1_GenInfo"],
    ["Employment_Employment_AP","Emp1_EmpAP"],
    ["Employment_Employment_GJ","Emp1_EmpGJ"],
    ["Employment_Employment_KN","Emp1_EmpKN"],
    ["Employment_Employment_MH","Emp1_EmpMH"],
    ["Employment_Employment_MP","Emp1_EmpMP"],
    ["GES_A.Household_details","GesA_HHDetails"],
    ["GES_B.Landholding_details","GesB_Landholding"],
    ["GES_C.Livestock_inv","GesC_Livestock"],
    ["GES_D.Farm_equipment","GesD_FarmEquip"],
    ["GES_E.Building","GesE_Building"],
    ["GES_E.Con_durables","GesE_ConDurables"],
    ["GES_E.Other_durables","GesE_OtherDurables"],
    ["GES_F.Stock_inv","GesF_StockInv"],
    ["GES_G.Debt_credit","GesG_FinAssLia"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_H.1.Gend_decision_making","GesI1_GendDM"],
    ["GES_H.2.Gend_crop_cult","GesI2_GendCult"],
    ["GES_I.1.Mart_info","GesJ1_MktInfo"],
    ["GES_I.2.Info_ranking","GesJ2_InfoRank"],
    ["GES_J.1_2.Coping_Mech","GesK12_CopingMech"],
    ["GES_J.3.Govt_assistance","GesK3_DroughAssist"],
    ["GES_J.4.How_reliable","GesJ4_ReliabilityRank"],
    ["GES_J.5.Proact_measures","GesJ5_Proactivity"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["Livestock_Fod_feed_pur","LS_FoodFed"],
    ["Livestock_gen_info","LS_GenInfo"],
    ["Livestock_Livestock","LS_Livestock"],
    ["MPrice_Commodities","MPrice_Commodities"],
    ["MPrice_Gen_info","MPrice_GenInfo"],
    ["MPrice_Machines","MPrice_Machines"],
    ["MPrice_Others","MPrice_Others"],
    ["MPrice_Seeds","MPrice_Seeds"],
    ["MPrice_Transport","MPrice_Transport"],
    ["MPrice_Wages","MPrice_Wages"],
    ["Plotlist_Gen_Info","PL1_GenInfo"],
    ["Plotlist_Plot_List","PL2_PlotList"],
    ["Transaction_Ben_govt_prog","Trans_BenGovtProg"],
    ["Transaction_Fin_Tran","Trans_FinTrans"],
    ["Transaction_Food_items_AP","Trans_FoodAP"],
    ["Transaction_Food_items_GJ","Trans_FoodGJ"],
    ["Transaction_Food_items_KN","Trans_FoodKN"],
    ["Transaction_Food_items_MH","Trans_FoodMH"],
    ["Transaction_Food_items_MP","Trans_FoodMP"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_gen_info","Trans_GenInfo"],
    ["Transaction_Non_food_items","Trans_NF"],
    ["Transaction_Prod_Sold","Trans_ProdSold"],
    ["Transaction_Sale_pur","Trans_SalePur"]]

rensSATIndia2012 = [
    ["Cultivation_1.Plot_Info","Cult1_PlotInfo"],
    ["Cultivation_2.Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_3.Cult_ip_AP","Cult3_ipAP"],
    ["Cultivation_3.Cult_ip_GJ","Cult3_ipGJ"],
    ["Cultivation_3.Cult_ip_KN","Cult3_ipKN"],
    ["Cultivation_3.Cult_ip_MH","Cult3_ipMH"],
    ["Cultivation_3.Cult_ip_MP","Cult3_ipMP"],
    ["Employment_1.K_gen_info","Emp1_GenInfo"],
    ["Employment_2.Employment_AP","Emp1_EmpAP"],
    ["Employment_2.Employment_GJ","Emp1_EmpGJ"],
    ["Employment_2.Employment_KN","Emp1_EmpKN"],
    ["Employment_2.Employment_MH","Emp1_EmpMH"],
    ["Employment_2.Employment_MP","Emp1_EmpMP"],
    ["GES_A.Household_details","GesA_HHDetails"],
    ["GES_B.Landholding_details","GesB_Landholding"],
    ["GES_C.Livestock_inv","GesC_Livestock"],
    ["GES_D.Farm_equipment","GesD_FarmEquip"],
    ["GES_E.Building","GesE_Building"],
    ["GES_E.Con_durables","GesE_ConDurables"],
    ["GES_E.Other_durables","GesE_OtherDurables"],
    ["GES_F.Stock_inv","GesF_StockInv"],
    ["GES_G.Debt_credit","GesG_FinAssLia"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_H.1.Gend_decision_making","GesI1_GendDM"],
    ["GES_H.2.Gend_crop_cult","GesI2_GendCult"],
    ["GES_I.1.Mart_info","GesJ1_MktInfo"],
    ["GES_I.2.Info_ranking","GesJ2_InfoRank"],
    ["GES_J.1_2.Coping_Mech","GesK12_CopingMech"],
    ["GES_J.3.Govt_assistance","GesK3_DroughAssist"],
    ["GES_J.4.How_reliable","GesJ4_ReliabilityRank"],
    ["GES_J.5.Proact_measures","GesJ5_Proactivity"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["Livestock_Fod_feed_pur","LS_FoodFed"],
    ["Livestock_Livestock","LS_Livestock"],
    ["Livestock_Z_gen_info","LS_GenInfo"],
    ["MPrice_1.M_gen_info","MPrice_GenInfo"],
    ["MPrice_2.Commodities","MPrice_Commodities"],
    ["MPrice_3.Transport","MPrice_Transport"],
    ["MPrice_4.Wages","MPrice_Wages"],
    ["MPrice_5.Machines","MPrice_Machines"],
    ["MPrice_6.Others","MPrice_Others"],
    ["MPrice_7.Seeds","MPrice_Seeds"],
    ["Plotlist_1.Gen_info","PL1_GenInfo"],
    ["Plotlist_2.Plot_list","PL2_PlotList"],
    ["Transaction_Ben_govt_prog","Trans_BenGovtProg"],
    ["Transaction_Fin_Tran","Trans_FinTrans"],
    ["Transaction_Food_items_AP","Trans_FoodAP"],
    ["Transaction_Food_items_GJ","Trans_FoodGJ"],
    ["Transaction_Food_items_KN","Trans_FoodKN"],
    ["Transaction_Food_items_MH","Trans_FoodMH"],
    ["Transaction_Food_items_MP","Trans_FoodMP"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_L_gen_info","Trans_GenInfo"],
    ["Transaction_Non_food_items_AP","Trans_NFAP"],
    ["Transaction_Non_food_items_GJ","Trans_NFGJ"],
    ["Transaction_Non_food_items_KN","Trans_NFKN"],
    ["Transaction_Non_food_items_MH","Trans_NFMH"],
    ["Transaction_Non_food_items_MP","Trans_NFMP"],
    ["Transaction_Prod_Sold","Trans_ProdSold"],
    ["Transaction_Sale_pur","Trans_SalePur"]]

rensSATIndia2013 = [
    ["Cultivation_1.Plot_info","Cult1_PlotInfo"],
    ["Cultivation_2.Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_3.Cult_ip_AP","Cult3_ipAP"],
    ["Cultivation_3.Cult_ip_GJ","Cult3_ipGJ"],
    ["Cultivation_3.Cult_ip_KN","Cult3_ipKN"],
    ["Cultivation_3.Cult_ip_MH","Cult3_ipMH"],
    ["Cultivation_3.Cult_ip_MP","Cult3_ipMP"],
    ["Employment_1.K_gen_info","Emp1_GenInfo"],
    ["Employment_2.Employment","Emp1_Emp"],
    ["GES_A.Household_details","GesA_HHDetails"],
    ["GES_B.Landholding_details","GesB_Landholding"],
    ["GES_C.Livestock_inv","GesC_Livestock"],
    ["GES_D.Farm_equipment","GesD_FarmEquip"],
    ["GES_E.Building","GesE_Building"],
    ["GES_E.Con_durables","GesE_ConDurables"],
    ["GES_E.Other_durables","GesE_OtherDurables"],
    ["GES_F.Stock_inv","GesF_StockInv"],
    ["GES_G.Debt_credit","GesG_FinAssLia"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_H.1.Gend_decision_making","GesI1_GendDM"],
    ["GES_H.2.Gend_crop_cult","GesI2_GendCult"],
    ["GES_I.1.Mart_info","GesJ1_MktInfo"],
    ["GES_I.2.Info_ranking","GesJ2_InfoRank"],
    ["GES_J.1_2.Coping_Mech","GesK12_CopingMech"],
    ["GES_J.3.Govt_assistance","GesK3_DroughAssist"],
    ["GES_J.4.How_reliable","GesJ4_ReliabilityRank"],
    ["GES_J.5.Proact_measures","GesJ5_Proactivity"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["Livestock_Fod_feed_pur","LS_FoodFed"],
    ["Livestock_Livestock","LS_Livestock"],
    ["Livestock_Z_gen_info","LS_GenInfo"],
    ["MPrice_1.M_gen_info","MPrice_GenInfo"],
    ["MPrice_2.Commodities","MPrice_Commodities"],
    ["MPrice_3.Transport","MPrice_Transport"],
    ["MPrice_4.Wages","MPrice_Wages"],
    ["MPrice_5.Machines","MPrice_Machines"],
    ["MPrice_6.Others","MPrice_Others"],
    ["MPrice_7.Seeds","MPrice_Seeds"],
    ["Plotlist_1.Gen_info","PL1_GenInfo"],
    ["Plotlist_2.Plot_list","PL2_PlotList"],
    ["Transaction_Ben_govt_prog","Trans_BenGovtProg"],
    ["Transaction_Fin_tran","Trans_FinTrans"],
    ["Transaction_Food_items_AP","Trans_FoodAP"],
    ["Transaction_Food_items_GJ","Trans_FoodGJ"],
    ["Transaction_Food_items_KN","Trans_FoodKN"],
    ["Transaction_Food_items_MH","Trans_FoodMH"],
    ["Transaction_Food_items_MP","Trans_FoodMP"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_L_gen_info","Trans_GenInfo"],
    ["Transaction_Non_food_items_AP","Trans_NFAP"],
    ["Transaction_Non_food_items_GJ","Trans_NFGJ"],
    ["Transaction_Non_food_items_KN","Trans_NFKN"],
    ["Transaction_Non_food_items_MH","Trans_NFMH"],
    ["Transaction_Non_food_items_MP","Trans_NFMP"],
    ["Transaction_Prod_sold","Trans_ProdSold"],
    ["Transaction_Sale_pur","Trans_SalePur"]]

rensSATIndia2014 = [
    ["Cultivation_1.Plot_info","Cult1_PlotInfo"],
    ["Cultivation_2.Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_3.Cult_ip","Cult3_ip1"],
    ["Employment_1.K_gen_info","Emp1_GenInfo"],
    ["Employment_2.Employment","Emp1_Emp"],
    ["GES_A.Household_details","GesA_HHDetails"],
    ["GES_B.Landholding_details","GesB_Landholding"],
    ["GES_C.Livestock_inv","GesC_Livestock"],
    ["GES_D.Farm_equipment","GesD_FarmEquip"],
    ["GES_E.Building","GesE_Building"],
    ["GES_E.Con_durables","GesE_ConDurables"],
    ["GES_E.Other_durables","GesE_OtherDurables"],
    ["GES_F.Stock_inv","GesF_StockInv"],
    ["GES_G.Debt_credit","GesG_FinAssLia"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_H.1.Gend_decision making","GesI1_GendDM"],
    ["GES_H.2.Gend_crop_cult","GesI2_GendCult"],
    ["GES_I.1.Mart_info","GesJ1_MktInfo"],
    ["GES_I.2.Info_ranking","GesJ2_InfoRank"],
    ["GES_J.1_2.Coping_Mech","GesK12_CopingMech"],
    ["GES_J.3.Govt_assistance","GesK3_DroughAssist"],
    ["GES_J.4.How_reliable","GesJ4_ReliabilityRank"],
    ["GES_J.5.Proact_measures","GesJ5_Proactivity"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["Livestock_Fod_feed_pur","LS_FoodFed"],
    ["Livestock_Livestock","LS_Livestock"],
    ["Livestock_Z_gen_info","LS_GenInfo"],
    ["MPrice_1.M_gen_info","MPrice_GenInfo"],
    ["MPrice_2.Commodities","MPrice_Commodities"],
    ["MPrice_3.Transport","MPrice_Transport"],
    ["MPrice_4.Wages","MPrice_Wages"],
    ["MPrice_5.Machines","MPrice_Machines"],
    ["MPrice_6.Others","MPrice_Others"],
    ["MPrice_7.Seeds","MPrice_Seeds"],
    ["Plotlist_1.Gen_info","PL1_GenInfo"],
    ["Plotlist_2.Plot_list","PL2_PlotList"],
    ["Rainfall_Daily Rainfall Data","Rain_DailyRainfall"],
    ["Transaction_Ben_govt_prog","Trans_BenGovtProg"],
    ["Transaction_Fin_tran","Trans_FinTrans"],
    ["Transaction_Food_items_AP","Trans_FoodAP"],
    ["Transaction_Food_items_GJ","Trans_FoodGJ"],
    ["Transaction_Food_items_KN","Trans_FoodKN"],
    ["Transaction_Food_items_MH","Trans_FoodMH"],
    ["Transaction_Food_items_MP","Trans_FoodMP"],
    ["Transaction_Food_items_TS","Trans_FoodTS"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_L_gen_info","Trans_GenInfo"],
    ["Transaction_Non_food_items","Trans_NF"],
    ["Transaction_Prod_sold","Trans_ProdSold"],
    ["Transaction_Sale_pur","Trans_SalePur"],
    ["HCS_1.Gen_info","HCS1_GenInfo"],
    ["HCS_2.Household_info","HCS2_HHInfo"],
    ["HCS_3.Oper_holding","HCS3_OperHolding"],
    ["HCS_4.Reso_farm_equip","HCS4_ResoFarmEquip"],
    ["HCS_4.Reso_livestock","HCS4_ResoLivestock"],
    ["HCS_4.Reso_res_house","HCS4_ResoResHouse"],
    ["HCS_5.Fam_Comp","HCS5_FamComp"],
    ["HCS_6.Emp_Status","HCS6_EmpStatus"],
    ["HCS_7.1.Govt_prog_participation","HCS71_GovtProgPart"],
    ["HCS_7.2.Bank_post_office accounts","HCS72_BankPOAccounts"],
    ["HCS_7.3.Loans_info","HCS73_LoansInfo"],
    ["HCS_7.4.PDS_facility_info","HCS74_PDSFacilityInfo"]]



rensEastIndia2010 = [
    ["Cultivation_Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_Cult_ip","Cult3_ip1"],
    ["Employment_Employment","Emp1_Emp"],
    ["GES_Building","GesE_Building"],
    ["GES_Con_Durables","GesE_ConDurables"],
    ["GES_Coping_Mech","GesK12_CopingMech"],
    ["GES_Drought_Assistance","GesK3_DroughAssist"],
    ["GES_Family_comp","GesA_HHDetails"],
    ["GES_Farm_equipment","GesD_FarmEquip"],
    ["GES_Fin_assets_liabilities","GesG_FinAssLia"],
    ["GES_Gend_crop_cult","GesI2_GendCult"],
    ["GES_Gend_decision_making","GesI1_GendDM"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_Govt_dev_Prog","GesJX_GovtDevProg"],
    ["GES_Info_ranking","GesJ2_InfoRank"],
    ["GES_Landholding_det","GesB_Landholding"],
    ["GES_Livestock_inv","GesC_Livestock"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["GES_Proactive_measure","GesJ5_Proactivity"],
    ["GES_Reliability_ranking","GesJ4_ReliabilityRank"],
    ["GES_Stock_inv","GesF_StockInv"],
    ["Livestock_Livestock","LS_Livestock"],
    ["Livestock_Pur_Food_Feeds","LS_FoodFed"],
    ["MPrice_Commodities","MPrice_Commodities"],
    ["MPrice_Machines","MPrice_Machines"],
    ["MPrice_Others","MPrice_Others"],
    ["MPrice_Transport","MPrice_Transport"],
    ["MPrice_Wages","MPrice_Wages"],
    ["Plotlist_Plotlist","PL2_PlotList"],
    ["Rainfall_Rainfall","Rain_DailyRainfall"],
    ["Transaction_Exp_food_non_food_BH","Trans_FoodNFBH"],
    ["Transaction_Exp_food_non_food_JH","Trans_FoodNFJH"],
    ["Transaction_Exp_food_non_food_OR","Trans_FoodNFOR"],
    ["Transaction_Fin_tran","Trans_FinTrans"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_Prod_sold","Trans_ProdSold"],
    ["Transaction_Sale_pur","Trans_SalePur"]]

rensEastIndia2011 = [
    ["Cultivation_Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_Cult_ip","Cult3_ip1"],
    ["Employment_Employment","Emp1_Emp"],
    ["GES_Building","GesE_Building"],
    ["GES_Con_Durables","GesE_ConDurables"],
    ["GES_Coping_Mech","GesK12_CopingMech"],
    ["GES_Drought_Assistance","GesK3_DroughAssist"],
    ["GES_Family_comp","GesA_HHDetails"],
    ["GES_Farm_equipment","GesD_FarmEquip"],
    ["GES_Fin_assets_liabilities","GesG_FinAssLia"],
    ["GES_Gend_crop_cult","GesI2_GendCult"],
    ["GES_Gend_decision_making","GesI1_GendDM"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_Govt_dev_Prog","GesJX_GovtDevProg"],
    ["GES_Info_ranking","GesJ2_InfoRank"],
    ["GES_Landholding_det","GesB_Landholding"],
    ["GES_Livestock_inv","GesC_Livestock"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["GES_Proactive_measure","GesJ5_Proactivity"],
    ["GES_Reliability_ranking","GesJ4_ReliabilityRank"],
    ["GES_Stock_inv","GesF_StockInv"],
    ["Livestock_Livestock","LS_Livestock"],
    ["Livestock_Pur_Food_Feeds","LS_FoodFed"],
    ["MPrice_Commodities","MPrice_Commodities"],
    ["MPrice_Machines","MPrice_Machines"],
    ["MPrice_Others","MPrice_Others"],
    ["MPrice_Transport","MPrice_Transport"],
    ["MPrice_Wages","MPrice_Wages"],
    ["Plotlist_Plotlist","PL2_PlotList"],
    ["Rainfall_Rainfall","Rain_DailyRainfall"],
    ["Transaction_Exp_food_non_food_BH","Trans_FoodNFBH"],
    ["Transaction_Exp_food_non_food_JH","Trans_FoodNFJH"],
    ["Transaction_Exp_food_non_food_OR","Trans_FoodNFOR"],
    ["Transaction_Fin_tran","Trans_FinTrans"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_Prod_sold","Trans_ProdSold"],
    ["Transaction_Sale_pur","Trans_SalePur"]]

rensEastIndia2012 = [
    ["Cultivation_Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_Cult_ip","Cult3_ip1"],
    ["Employment_Employment","Emp1_Emp"],
    ["GES_Building","GesE_Building"],
    ["GES_Con_Durables","GesE_ConDurables"],
    ["GES_Coping_Mech","GesK12_CopingMech"],
    ["GES_Drought_Assistance","GesK3_DroughAssist"],
    ["GES_Family_comp","GesA_HHDetails"],
    ["GES_Farm_equipment","GesD_FarmEquip"],
    ["GES_Fin_assets_liabilities","GesG_FinAssLia"],
    ["GES_Gend_crop_cult","GesI2_GendCult"],
    ["GES_Gend_decision_making","GesI1_GendDM"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_Govt_dev_Prog","GesJX_GovtDevProg"],
    ["GES_Info_ranking","GesJ2_InfoRank"],
    ["GES_Landholding_det","GesB_Landholding"],
    ["GES_Livestock_inv","GesC_Livestock"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["GES_Proactive_measure","GesJ5_Proactivity"],
    ["GES_Reliability_ranking","GesJ4_ReliabilityRank"],
    ["GES_Stock_inv","GesF_StockInv"],
    ["Livestock_Livestock","LS_Livestock"],
    ["Livestock_Pur_Fod_Feeds","LS_FoodFed"],
    ["MPrice_Commodities","MPrice_Commodities"],
    ["MPrice_Machines","MPrice_Machines"],
    ["MPrice_Others","MPrice_Others"],
    ["MPrice_Transport","MPrice_Transport"],
    ["MPrice_Wages","MPrice_Wages"],
    ["Plotlist_Plotlist","PL2_PlotList"],
    ["Rainfall_Rainfall","Rain_DailyRainfall"],
    ["Transaction_Exp_food_non_food_BH","Trans_FoodNFBH"],
    ["Transaction_Exp_food_non_food_JH","Trans_FoodNFJH"],
    ["Transaction_Exp_food_non_food_OR","Trans_FoodNFOR"],
    ["Transaction_Fin_tran","Trans_FinTrans"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_Prod_sold","Trans_ProdSold"],
    ["Transaction_Sale_pur","Trans_SalePur"]]

rensEastIndia2013 = [
    ["Cultivation_Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_Cult_ip","Cult3_ip1"],
    ["Employment_Employment","Emp1_Emp"],
    ["GES_Building","GesE_Building"],
    ["GES_Con_Durables","GesE_ConDurables"],
    ["GES_Coping_Mech","GesK12_CopingMech"],
    ["GES_Drought_Assistance","GesK3_DroughAssist"],
    ["GES_Family_comp","GesA_HHDetails"],
    ["GES_Farm_Equipment","GesD_FarmEquip"],
    ["GES_Fin_assets_liabilities","GesG_FinAssLia"],
    ["GES_Gend_crop_cult","GesI2_GendCult"],
    ["GES_Gend_decision_making","GesI1_GendDM"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_Gov_dev_prog","GesJX_GovtDevProg"],
    ["GES_Info_ranking","GesJ2_InfoRank"],
    ["GES_Landholding_det","GesB_Landholding"],
    ["GES_Livestock_inv","GesC_Livestock"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["GES_Proactive_measure","GesJ5_Proactivity"],
    ["GES_Reliability_ranking","GesJ4_ReliabilityRank"],
    ["GES_Stock_inv","GesF_StockInv"],
    ["Livestock_Livestock","LS_Livestock"],
    ["Livestock_Pur_Fod_Feeds","LS_FoodFed"],
    ["MPrice_Comodity","MPrice_Commodities"],
    ["MPrice_Machine","MPrice_Machines"],
    ["MPrice_Others","MPrice_Others"],
    ["MPrice_Transport","MPrice_Transport"],
    ["MPrice_Wages","MPrice_Wages"],
    ["Plotlist_Plot_list","PL2_PlotList"],
    ["Rainfall_Rainfall","Rain_DailyRainfall"],
    ["Transaction_Exp_food_non_food_BH","Trans_FoodNFBH"],
    ["Transaction_Exp_food_non_food_JH","Trans_FoodNFJH"],
    ["Transaction_Exp_food_non_food_OR","Trans_FoodNFOR"],
    ["Transaction_Fin_tran","Trans_FinTrans"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_Prod_Sold","Trans_ProdSold"],
    ["Transaction_Sale_pur","Trans_SalePur"]]

rensEastIndia2014 = [
    ["Cultivation_Cult_output","Cult2_CropInfo"],
    ["Cultivation_Cult_input","Cult3_ip1"],
    ["Employment_Employment","Emp1_Emp"],
    ["GES_Building","GesE_Building"],
    ["GES_Consumer_durabale","GesE_ConDurables"],
    ["GES_Coping_mech","GesK12_CopingMech"],
    ["GES_Drought_assistant","GesK3_DroughAssist"],
    ["GES_Family_comp","GesA_HHDetails"],
    ["GES_Farm_equpment","GesD_FarmEquip"],
    ["GES_Fin_assets_liabilities","GesG_FinAssLia"],
    ["GES_Gend_crop_cult","GesI2_GendCult"],
    ["GES_Gend_decision_making","GesI1_GendDM"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_Govt_dev_prog","GesJX_GovtDevProg"],
    ["GES_Info_ranking","GesJ2_InfoRank"],
    ["GES_Landholding_det","GesB_Landholding"],
    ["GES_Livestock_inv","GesC_Livestock"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["GES_Productive_measure","GesJ5_Proactivity"],
    ["GES_Relability_ranking","GesJ4_ReliabilityRank"],
    ["GES_Stock_inv","GesF_StockInv"],
    ["Livestock_Livestock_economics","LS_Livestock"],
    ["Livestock_Pur_Fod_Feeds","LS_FoodFed"],
    ["MPrice_Commodity","MPrice_Commodities"],
    ["MPrice_Machine","MPrice_Machines"],
    ["MPrice_Other","MPrice_Others"],
    ["MPrice_Transport","MPrice_Transport"],
    ["MPrice_Wages","MPrice_Wages"],
    ["Plotlist_Plot_List","PL2_PlotList"],
    ["Rainfall_Rainfall","Rain_DailyRainfall"],
    ["Transaction_Exp_food_non_food","Trans_FoodNF"],
    ["Transaction_Fin_tran","Trans_FinTrans"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_Prod_Sold","Trans_ProdSold"],
    ["Transaction_Sale_pur","Trans_SalePur"]
]


rensBang2009 = [
    ["Cultivation_Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_Cult_ip","Cult3_ip1"],
    ["Employment_Employment_Begumupur","Emp1_EmpBegumP"],
    ["Employment_Employment_Bhabanipur","Emp1_EmpBhabaniP"],
    ["Employment_Employment_Boikunthipur","Emp1_EmpBoikunthiP"],
    ["Employment_Employment_Darikamari","Emp1_EmpDarikamari"],
    ["Employment_Employment_DKabirK","Emp1_EmpDKabirK"],
    ["Employment_Employment_Khudiakhali","Emp1_EmpKhudiaK"],
    ["Employment_Employment_Konapara","Emp1_EmpKonapara"],
    ["Employment_Employment_Niamotpur","Emp1_EmpNiamotP"],
    ["Employment_Employment_Nisaiganj","Emp1_EmpNishaiganj"],
    ["Employment_Employment_Patordia","Emp1_EmpPatordia"],
    ["Employment_Employment_PBahadurP","Emp1_EmpPBahadurP"],
    ["Employment_Employment_RSimulB","Emp1_EmpRShimulB"],
    ["GES_Building","GesE_Building"],
    ["GES_Con_Durables","GesE_ConDurables"],
    ["GES_Coping_Mech","GesK12_CopingMech"],
    ["GES_Drought_Assistance","GesK3_DroughAssist"],
    ["GES_Family_comp","GesA_HHDetails"],
    ["GES_Farm_equipment","GesD_FarmEquip"],
    ["GES_Fin_assets_liabilities","GesG_FinAssLia"],
    ["GES_Gend_crop_cult","GesI2_GendCult"],
    ["GES_Gend_decision_making","GesI1_GendDM"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_Govt_dev_prog","GesJX_GovtDevProg"],
    ["GES_Info_ranking","GesJ2_InfoRank"],
    ["GES_Landholding_det","GesB_Landholding"],
    ["GES_Livestock_inv","GesC_Livestock"],
    ["GES_Market_info","GesJ1_MktInfo"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["GES_Stock_inv","GesF_StockInv"],
    ["Livestock_Livestock","LS_Livestock"],
    ["MPrice_Commodities","MPrice_Commodities"],
    ["MPrice_Machines","MPrice_Machines"],
    ["MPrice_Others","MPrice_Others"],
    ["MPrice_Transport","MPrice_Transport"],
    ["MPrice_Wages","MPrice_Wages"],
    ["Plotlist_GES_Market_Info_1_1","PLGes_MktInfo1"],
    ["Plotlist_GES_Market_Info_1_2","PLGes_MktInfo2"],
    ["Plotlist_GES_Market_Info_2_2","PLGes_MktInfo3"],
    ["Plotlist_GES_Market_Info_4","PLGes_MktInfo4"],
    ["Plotlist_Info_faci_rating","GesJ3_InfoFacilityRating"],
    ["Plotlist_Plotlist","PL2_PlotList"],
    ["Transaction_Business_Caste_Income","Trans_BusiCaCo"],
    ["Transaction_Exp_food_non_food_Begump","Trans_FoodNFBegum"],
    ["Transaction_Exp_food_non_food_Bhabani","Trans_FoodNFBhabani"],
    ["Transaction_Exp_food_non_food_Boikunthi","Trans_FoodNFBoikunthi"],
    ["Transaction_Exp_food_non_food_DarikaM","Trans_FoodNFDarikaM"],
    ["Transaction_Exp_food_non_food_DKabirK","Trans_FoodNFDKabirK"],
    ["Transaction_Exp_food_non_food_KhudiaK","Trans_FoodNFKhudiaK"],
    ["Transaction_Exp_food_non_food_Konapara","Trans_FoodNFKonapara"],
    ["Transaction_Exp_food_non_food_NiamotP","Trans_FoodNFNiamotP"],
    ["Transaction_Exp_food_non_food_Nishaiganj","Trans_FoodNFNishaiganj"],
    ["Transaction_Exp_food_non_food_Patordia","Trans_FoodNFPatordia"],
    ["Transaction_Exp_food_non_food_PBahadurP","Trans_FoodNFPBahadurP"],
    ["Transaction_Exp_food_non_food_RShimulB","Trans_FoodNFRShimulB"],
    ["Transaction_Fin_tran","Trans_FinTrans"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_Sale_pur","Trans_SalePur"],
    ["HCS_Family_composition","HCS_Family_composition"],
    ["HCS_Gen_info","HCS1_GenInfo"],
    ["HCS_Household_info","HCS2_HHInfo"],
    ["HCS_Immediate_relative","HCS5_FamComp"],
    ["HCS_Land_holding","HCS3_OperHolding"],
    ["HCS_Reso_farm_equipment","HCS4_ResoFarmEquip"],
    ["HCS_Reso_livestock","HCS4_ResoLivestock"]]

rensBang2010 = [
    ["Cultivation_Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_Cult_ip_BegumP","Cult3_ipBegum"],
    ["Cultivation_Cult_ip_BhabaniP","Cult3_ipBhab"],
    ["Cultivation_Cult_ip_BoikunthiP","Cult3_ipBoik"],
    ["Cultivation_Cult_ip_DarikaM","Cult3_ipDarikm"],
    ["Cultivation_Cult_ip_DKabirK","Cult3_ipDkk"],
    ["Cultivation_Cult_ip_KhudiaK","Cult3_ipKhudia"],
    ["Cultivation_Cult_ip_Konapara","Cult3_ipKonapara"],
    ["Cultivation_Cult_ip_Niamotpur","Cult3_ipNiamat"],
    ["Cultivation_Cult_ip_Nishaiganj","Cult3_ipNisha"],
    ["Cultivation_Cult_ip_Patordia","Cult3_ipPatord"],
    ["Cultivation_Cult_ip_PBahadurP","Cult3_ipPB"],
    ["Cultivation_Cult_ip_RShimulB","Cult3_ipRSB"],
    ["Employment_Employment_BegumP","Emp1_EmpBegumP"],
    ["Employment_Employment_BhabaniP","Emp1_EmpBhabaniP"],
    ["Employment_Employment_BoikunthiP","Emp1_EmpBoikunthiP"],
    ["Employment_Employment_Darikamari","Emp1_EmpDarikamari"],
    ["Employment_Employment_DKabirK","Emp1_EmpDKabirK"],
    ["Employment_Employment_KhudiaK","Emp1_EmpKhudiaK"],
    ["Employment_Employment_Konapara","Emp1_EmpKonapara"],
    ["Employment_Employment_NiamotP","Emp1_EmpNiamotP"],
    ["Employment_Employment_Nishaiganj","Emp1_EmpNishaiganj"],
    ["Employment_Employment_Patordia","Emp1_EmpPatordia"],
    ["Employment_Employment_PBahadurP","Emp1_EmpPBahadurP"],
    ["Employment_Employment_RShimulB","Emp1_EmpRShimulB"],
    ["GES_Building","GesE_Building"],
    ["GES_Con_Durables","GesE_ConDurables"],
    ["GES_Coping_Mech","GesK12_CopingMech"],
    ["GES_Drought_Assistance","GesK3_DroughAssist"],
    ["GES_Family_comp","GesA_HHDetails"],
    ["GES_Farm_equipment","GesD_FarmEquip"],
    ["GES_Fin_assets_liabilities","GesG_FinAssLia"],
    ["GES_Gend_crop_cult","GesI2_GendCult"],
    ["GES_Gend_decision_making","GesI1_GendDM"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_Govt_dev_prog","GesJX_GovtDevProg"],
    ["GES_Info_ranking","GesJ2_InfoRank"],
    ["GES_Landholding_det","GesB_Landholding"],
    ["GES_Livestock_inv","GesC_Livestock"],
    ["GES_Market_info","GesJ1_MktInfo"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["GES_Stock_inv","GesF_StockInv"],
    ["Livestock_Livestock","LS_Livestock"],
    ["MPrice_Commodities","MPrice_Commodities"],
    ["MPrice_Machines","MPrice_Machines"],
    ["MPrice_Others","MPrice_Others"],
    ["MPrice_Transport","MPrice_Transport"],
    ["MPrice_Wages","MPrice_Wages"],
    ["Plotlist_GES_Market_Info_1_1","PLGes_MktInfo1"],
    ["Plotlist_GES_Market_Info_1_2","PLGes_MktInfo2"],
    ["Plotlist_GES_Market_Info_2_2","PLGes_MktInfo3"],
    ["Plotlist_GES_Market_Info_4","PLGes_MktInfo4"],
    ["Plotlist_Info_faci_rating","GesJ3_InfoFacilityRating"],
    ["Plotlist_Plotlist","PL2_PlotList"],
    ["Transaction_Business_Caste_Income","Trans_BusiCaCo"],
    ["Transaction_Exp_food_non_food_Begum","Trans_FoodNFBegum"],
    ["Transaction_Exp_food_non_food_Bhabani","Trans_FoodNFBhabani"],
    ["Transaction_Exp_food_non_food_BoikunthiP","Trans_FoodNFBoikunthi"],
    ["Transaction_Exp_food_non_food_DarikaM","Trans_FoodNFDarikaM"],
    ["Transaction_Exp_food_non_food_DKabirK","Trans_FoodNFDKabirK"],
    ["Transaction_Exp_food_non_food_KhudiaK","Trans_FoodNFKhudiaK"],
    ["Transaction_Exp_food_non_food_Konapara","Trans_FoodNFKonapara"],
    ["Transaction_Exp_food_non_food_NiamotP","Trans_FoodNFNiamotP"],
    ["Transaction_Exp_food_non_food_Nishaiganj","Trans_FoodNFNishaiganj"],
    ["Transaction_Exp_food_non_food_Patordia","Trans_FoodNFPatordia"],
    ["Transaction_Exp_food_non_food_PBahadurP","Trans_FoodNFPBahadurP"],
    ["Transaction_Exp_food_non_food_RShimulB","Trans_FoodNFRShimulB"],
    ["Transaction_Fin_tran","Trans_FinTrans"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_Sale_pur","Trans_SalePur"]]

rensBang2011 = [
    ["Cultivation_Crop_info_op","Cult2_CropInfo"],
    ["Cultivation_Cult_ip2011_Begum","Cult3_ipBegum"],
    ["Cultivation_Cult_ip2011_Bhabani","Cult3_ipBhab"],
    ["Cultivation_Cult_ip2011_Boikunth","Cult3_ipBoik"],
    ["Cultivation_Cult_ip2011_DariKM","Cult3_ipDarikm"],
    ["Cultivation_Cult_ip2011_DKabirK","Cult3_ipDkk"],
    ["Cultivation_Cult_ip2011_Khudia","Cult3_ipKhudia"],
    ["Cultivation_Cult_ip2011_Konapara","Cult3_ipKonapara"],
    ["Cultivation_Cult_ip2011_Niamotpur","Cult3_ipNiamat"],
    ["Cultivation_Cult_ip2011_Nishaiganj","Cult3_ipNisha"],
    ["Cultivation_Cult_ip2011_Patordia","Cult3_ipPatord"],
    ["Cultivation_Cult_ip2011_PBahadurpur","Cult3_ipPB"],
    ["Cultivation_Cult_ip2011_RShimulB","Cult3_ipRSB"],
    ["Employment_Employment","Emp1_Emp"],
    ["GES_Building","GesE_Building"],
    ["GES_Con_Durables","GesE_ConDurables"],
    ["GES_Coping_Mech","GesK12_CopingMech"],
    ["GES_Drought_Assistance","GesK3_DroughAssist"],
    ["GES_Family_comp","GesA_HHDetails"],
    ["GES_Farm_equipment","GesD_FarmEquip"],
    ["GES_Fin_assets_liabilities","GesG_FinAssLia"],
    ["GES_Gend_crop_cult","GesI2_GendCult"],
    ["GES_Gend_decision_making","GesI1_GendDM"],
    ["GES_Gen_info","Ges_GenInfo"],
    ["GES_Govt_dev_prog","GesJX_GovtDevProg"],
    ["GES_Info_ranking","GesJ2_InfoRank"],
    ["GES_Landholding_det","GesB_Landholding"],
    ["GES_Livestock_inv","GesC_Livestock"],
    ["GES_Market_info","GesJ1_MktInfo"],
    ["GES_Oper_holding","Ges_OperHolding"],
    ["GES_Stock_inv","GesF_StockInv"],
    ["Livestock_Livestock","LS_Livestock"],
    ["Mprice_Commodity","MPrice_Commodities"],
    ["Mprice_Machines","MPrice_Machines"],
    ["Mprice_Others","MPrice_Others"],
    ["Mprice_Transport","MPrice_Transport"],
    ["Mprice_Wages","MPrice_Wages"],
    ["Plotlist_GES_Market_Info_1_1","PLGes_MktInfo1"],
    ["Plotlist_GES_Market_Info_1_2","PLGes_MktInfo2"],
    ["Plotlist_GES_Market_Info_2_2","PLGes_MktInfo3"],
    ["Plotlist_GES_Market_Info_4","PLGes_MktInfo4"],
    ["Plotlist_Info_faci_rating","GesJ3_InfoFacilityRating"],
    ["Plotlist_Plotlist","PL2_PlotList"],
    ["Transaction_Business_Caste_Income","Trans_BusiCaCo"],
    ["Transaction_Exp_food_non_food_Begum","Trans_FoodNFBegum"],
    ["Transaction_Exp_food_non_food_Bhabani","Trans_FoodNFBhabani"],
    ["Transaction_Exp_food_non_food_Boikunth","Trans_FoodNFBoikunthi"],
    ["Transaction_Exp_food_non_food_DariKM","Trans_FoodNFDarikaM"],
    ["Transaction_Exp_food_non_food_DKabirK","Trans_FoodNFDKabirK"],
    ["Transaction_Exp_food_non_food_Khudia","Trans_FoodNFKhudiaK"],
    ["Transaction_Exp_food_non_food_Konapara","Trans_FoodNFKonapara"],
    ["Transaction_Exp_food_non_food_Niamotpur","Trans_FoodNFNiamotP"],
    ["Transaction_Exp_food_non_food_Nishaiganj","Trans_FoodNFNishaiganj"],
    ["Transaction_Exp_food_non_food_Patordia","Trans_FoodNFPatordia"],
    ["Transaction_Exp_food_non_food_PBahadurpur","Trans_FoodNFPBahadurP"],
    ["Transaction_Exp_food_non_food_RShimulB","Trans_FoodNFRShimulB"],
    ["Transaction_Fin_tran","Trans_FinTrans"],
    ["Transaction_Loans","Trans_Loans"],
    ["Transaction_Sale_pur","Trans_SalePur"]]

rensBang2012 = [
    ["Cultivation_Crop_info_op_12","Cult2_CropInfo"],
    ["Cultivation_Cult_ip_12_Begumpur","Cult3_ipBegum"],
    ["Cultivation_Cult_ip_12_Bhabanipur","Cult3_ipBhab"],
    ["Cultivation_Cult_ip_12_Boikunthapur","Cult3_ipBoik"],
    ["Cultivation_Cult_ip_12_DakkhinKabirKathi","Cult3_ipDkk"],
    ["Cultivation_Cult_ip_12_Dharikamari","Cult3_ipDarikm"],
    ["Cultivation_Cult_ip_12_Khudiakhali","Cult3_ipKhudia"],
    ["Cultivation_Cult_ip_12_Konapara","Cult3_ipKonapara"],
    ["Cultivation_Cult_ip_12_Niamatpur","Cult3_ipNiamat"],
    ["Cultivation_Cult_ip_12_Nishaiganj","Cult3_ipNisha"],
    ["Cultivation_Cult_ip_12_PaschimBahadurpur","Cult3_ipPB"],
    ["Cultivation_Cult_ip_12_Patordia","Cult3_ipPatord"],
    ["Cultivation_Cult_ip_12_RasunShimulbari","Cult3_ipRSB"],
    ["Employment_Employment_12","Emp1_Emp"],
    ["GES_Building_12","GesE_Building"],
    ["GES_Con_Durables_12","GesE_ConDurables"],
    ["GES_Coping_Mech_12","GesK12_CopingMech"],
    ["GES_Drought_Assistance_12","GesK3_DroughAssist"],
    ["GES_Family_comp_12","GesA_HHDetails"],
    ["GES_Farm_equipment_12","GesD_FarmEquip"],
    ["GES_Fin_assets_liabilities_12","GesG_FinAssLia"],
    ["GES_Gend_crop_cult_12","GesI2_GendCult"],
    ["GES_Gend_decision_making_12","GesI1_GendDM"],
    ["GES_Gen_info_12","Ges_GenInfo"],
    ["GES_Govt_dev_prog_12","GesJX_GovtDevProg"],
    ["GES_Info_ranking_12","GesJ2_InfoRank"],
    ["GES_Landholding_det_12","GesB_Landholding"],
    ["GES_Livestock_inv_12","GesC_Livestock"],
    ["GES_Market_info_12","GesJ1_MktInfo"],
    ["GES_Oper_holding_12","Ges_OperHolding"],
    ["GES_Stock_inv_12","GesF_StockInv"],
    ["Livestock_Livestock_12","LS_Livestock"],
    ["Mprice_Commodity_12","MPrice_Commodities"],
    ["Mprice_Machines_12","MPrice_Machines"],
    ["Mprice_Others_12","MPrice_Others"],
    ["Mprice_Transport_12","MPrice_Transport"],
    ["Mprice_Wages_12","MPrice_Wages"],
    ["Plotlist_GES_Market_Info_1_1_12","PLGes_MktInfo1"],
    ["Plotlist_GES_Market_Info_1_2_12","PLGes_MktInfo2"],
    ["Plotlist_GES_Market_Info_2_2_12","PLGes_MktInfo3"],
    ["Plotlist_GES_Market_Info_4_12","PLGes_MktInfo4"],
    ["Plotlist_Info_faci_rating_12","GesJ3_InfoFacilityRating"],
    ["Plotlist_Plotlist_CroppingPattern_12","PL2_PlotList"],
    ["Transaction_Business_Caste_Income_12","Trans_BusiCaCo"],
    ["Transaction_Exp_food_non_food_Begum","Trans_FoodNFBegum"],
    ["Transaction_Exp_food_non_food_Bhabani","Trans_FoodNFBhabani"],
    ["Transaction_Exp_food_non_food_Boikunth","Trans_FoodNFBoikunthi"],
    ["Transaction_Exp_food_non_food_DariKM","Trans_FoodNFDarikaM"],
    ["Transaction_Exp_food_non_food_DKabirK","Trans_FoodNFDKabirK"],
    ["Transaction_Exp_food_non_food_Khudia","Trans_FoodNFKhudiaK"],
    ["Transaction_Exp_food_non_food_Konapara","Trans_FoodNFKonapara"],
    ["Transaction_Exp_food_non_food_Niamotpur","Trans_FoodNFNiamotP"],
    ["Transaction_Exp_food_non_food_Nishaiganj","Trans_FoodNFNishaiganj"],
    ["Transaction_Exp_food_non_food_Patordia","Trans_FoodNFPatordia"],
    ["Transaction_Exp_food_non_food_PBahadurpur","Trans_FoodNFPBahadurP"],
    ["Transaction_Exp_food_non_food_RShimulB","Trans_FoodNFRShimulB"],
    ["Transaction_Fin_tran_12","Trans_FinTrans"],
    ["Transaction_Loans_12","Trans_Loans"],
    ["Transaction_Sale_pur_12","Trans_SalePur"]]

rensBang2013 = [
    ["Cultivation_Crop_info_op_13","Cult2_CropInfo"],
    ["Cultivation_Cult_ip_13 RasunShimul Bari","Cult3_ipRSB"],
    ["Cultivation_Cult_ip_13_Begumpur","Cult3_ipBegum"],
    ["Cultivation_Cult_ip_13_Bhabanipur","Cult3_ipBhab"],
    ["Cultivation_Cult_ip_13_Boikunthipur","Cult3_ipBoik"],
    ["Cultivation_Cult_ip_13_Darikamari","Cult3_ipDarikm"],
    ["Cultivation_Cult_ip_13_DKabirKathi","Cult3_ipDkk"],
    ["Cultivation_Cult_ip_13_Khudiakhali","Cult3_ipKhudia"],
    ["Cultivation_Cult_ip_13_Konapara","Cult3_ipKonapara"],
    ["Cultivation_Cult_ip_13_Niamotpur","Cult3_ipNiamat"],
    ["Cultivation_Cult_ip_13_Nishaiganj","Cult3_ipNisha"],
    ["Cultivation_Cult_ip_13_PaschimBahadurpur","Cult3_ipPB"],
    ["Cultivation_Cult_ip_13_Patordia","Cult3_ipPatord"],
    ["Employment_Employment_13","Emp1_Emp"],
    ["GES_Building_13","GesE_Building"],
    ["GES_Con_Durables_13","GesE_ConDurables"],
    ["GES_Coping_Mech_13","GesK12_CopingMech"],
    ["GES_Drought_Assistance_13","GesK3_DroughAssist"],
    ["GES_Family_comp_13","GesA_HHDetails"],
    ["GES_Farm_equipment_13","GesD_FarmEquip"],
    ["GES_Fin_assets_liabilities_13","GesG_FinAssLia"],
    ["GES_Gend_crop_cult_13","GesI2_GendCult"],
    ["GES_Gend_decision_making_13","GesI1_GendDM"],
    ["GES_Gen_info_13","Ges_GenInfo"],
    ["GES_Govt_dev_prog_13","GesJX_GovtDevProg"],
    ["GES_Info_ranking_13","GesJ2_InfoRank"],
    ["GES_Landholding_det_13","GesB_Landholding"],
    ["GES_Livestock_inv_13","GesC_Livestock"],
    ["GES_Market_info_13","GesJ1_MktInfo"],
    ["GES_Oper_holding_13","Ges_OperHolding"],
    ["GES_Stock_inv_13","GesF_StockInv"],
    ["Livestock_Livestock_13","LS_Livestock"],
    ["MPrice_Commodity_13","MPrice_Commodities"],
    ["MPrice_Machines_13","MPrice_Machines"],
    ["MPrice_Others_13","MPrice_Others"],
    ["MPrice_Transport_13","MPrice_Transport"],
    ["MPrice_Wages_13","MPrice_Wages"],
    ["Plotlist_GES_Market_Info_1_1_13","PLGes_MktInfo1"],
    ["Plotlist_GES_Market_Info_1_2_13","PLGes_MktInfo2"],
    ["Plotlist_GES_Market_Info_2_2_13","PLGes_MktInfo3"],
    ["Plotlist_GES_Market_Info_4_13","PLGes_MktInfo4"],
    ["Plotlist_Info_faci_rating_13","GesJ3_InfoFacilityRating"],
    ["Plotlist_Plotlist_13","PL2_PlotList"],
    ["Transaction_Business_Caste_Income_13","Trans_BusiCaCo"],
    ["Transaction_Exp_food_non_food_Begumpur","Trans_FoodNFBegum"],
    ["Transaction_Exp_food_non_food_Bhabanipur","Trans_FoodNFBhabani"],
    ["Transaction_Exp_food_non_food_Boikunthipur","Trans_FoodNFBoikunthi"],
    ["Transaction_Exp_food_non_food_Darikamari","Trans_FoodNFDarikaM"],
    ["Transaction_Exp_food_non_food_DKabirKathi","Trans_FoodNFDKabirK"],
    ["Transaction_Exp_food_non_food_Khudiakhali","Trans_FoodNFKhudiaK"],
    ["Transaction_Exp_food_non_food_Konapara","Trans_FoodNFKonapara"],
    ["Transaction_Exp_food_non_food_Niamotpur","Trans_FoodNFNiamotP"],
    ["Transaction_Exp_food_non_food_Nishaiganj","Trans_FoodNFNishaiganj"],
    ["Transaction_Exp_food_non_food_PaschimBahadurpur","Trans_FoodNFPBahadurP"],
    ["Transaction_Exp_food_non_food_Patordia","Trans_FoodNFPatordia"],
    ["Transaction_Exp_food_non_food_RasunShimulBari","Trans_FoodNFRShimulB"],
    ["Transaction_Fin_tran_13","Trans_FinTrans"],
    ["Transaction_Loans_13","Trans_Loans"],
    ["Transaction_Sale_pur_13","Trans_SalePur"]]

rensBang2014 = [
    ["Cultivation_Crop_info_op_14","Cult2_CropInfo"],
    ["Cultivation_Cult_ip_14 Begumpur","Cult3_ipBegum"],
    ["Cultivation_Cult_ip_14 Bhabaipur","Cult3_ipBhab"],
    ["Cultivation_Cult_ip_14 Boikunthipur","Cult3_ipBoik"],
    ["Cultivation_Cult_ip_14 D.Kabir Kathi","Cult3_ipDkk"],
    ["Cultivation_Cult_ip_14 Darikamari","Cult3_ipDarikm"],
    ["Cultivation_Cult_ip_14 Khudiakhali","Cult3_ipKhudia"],
    ["Cultivation_Cult_ip_14 Konapara","Cult3_ipKonapara"],
    ["Cultivation_Cult_ip_14 Niamotpur","Cult3_ipNiamat"],
    ["Cultivation_Cult_ip_14 Nishaiganj","Cult3_ipNisha"],
    ["Cultivation_Cult_ip_14 Paschim Bahadurpur","Cult3_ipPB"],
    ["Cultivation_Cult_ip_14 Patordia","Cult3_ipPatord"],
    ["Cultivation_Cult_ip_14 Rasun Shimul Bari","Cult3_ipRSB"],
    ["Employment_Employment_14","Emp1_Emp"],
    ["GES_Building_14","GesE_Building"],
    ["GES_Con_ Durables_14","GesE_ConDurables"],
    ["GES_Coping _Mech_14","GesK12_CopingMech"],
    ["GES_Draught_Assistance_14","GesK3_DroughAssist"],
    ["GES_Family_comp_14","GesA_HHDetails"],
    ["GES_Farm_equipment_14","GesD_FarmEquip"],
    ["GES_Fin_assets_liabilities_14","GesG_FinAssLia"],
    ["GES_Gend_crop_cult_14","GesI2_GendCult"],
    ["GES_Gend_decision_making_14","GesI1_GendDM"],
    ["GES_Gen_info_14","Ges_GenInfo"],
    ["GES_Govt_dev_prog_14","GesJX_GovtDevProg"],
    ["GES_Info_ranking_14","GesJ2_InfoRank"],
    ["GES_Landholding_det_14","GesB_Landholding"],
    ["GES_Livestock_inv_14","GesC_Livestock"],
    ["GES_Market_info_14","GesJ1_MktInfo"],
    ["GES_Oper_holding_14","Ges_OperHolding"],
    ["GES_Stock_inv_14","GesF_StockInv"],
    ["Livestock_Z-Livestock-2014-15","LS_Livestock"],
    ["MPrice_Commodity_14","MPrice_Commodities"],
    ["MPrice_Machines_14","MPrice_Machines"],
    ["MPrice_Others_14","MPrice_Others"],
    ["MPrice_Transport_14","MPrice_Transport"],
    ["MPrice_Wages_14","MPrice_Wages"],
    ["Plotlist_GES_Market_Info_1_1_14","PLGes_MktInfo1"],
    ["Plotlist_GES_Market_Info_1_2_14","PLGes_MktInfo2"],
    ["Plotlist_GES_Market_Info_2_2_14","PLGes_MktInfo3"],
    ["Plotlist_GES_Market_Info_4_14","PLGes_MktInfo4"],
    ["Plotlist_Info_faci_rating_14","GesJ3_InfoFacilityRating"],
    ["Plotlist_Plot List-2014-2015","PL2_PlotList"],
    ["Transaction_Business_Caste_Income_14","Trans_BusiCaCo"],
    ["Transaction_Exp_food_non_food_14 Begumpur","Trans_FoodNFBegum"],
    ["Transaction_Exp_food_non_food_14 Bhabanipur","Trans_FoodNFBhabani"],
    ["Transaction_Exp_food_non_food_14 Boikunthipur","Trans_FoodNFBoikunthi"],
    ["Transaction_Exp_food_non_food_14 D.Kabir Kathi","Trans_FoodNFDKabirK"],
    ["Transaction_Exp_food_non_food_14 Darikamari","Trans_FoodNFDarikaM"],
    ["Transaction_Exp_food_non_food_14 Khudiakhali","Trans_FoodNFKhudiaK"],
    ["Transaction_Exp_food_non_food_14 Konapara","Trans_FoodNFKonapara"],
    ["Transaction_Exp_food_non_food_14 Niamotpur","Trans_FoodNFNiamotP"],
    ["Transaction_Exp_food_non_food_14 Nishaiganj","Trans_FoodNFNishaiganj"],
    ["Transaction_Exp_food_non_food_14 Paschim Bahadurpur","Trans_FoodNFPBahadurP"],
    ["Transaction_Exp_food_non_food_14 Patordia","Trans_FoodNFPatordia"],
    ["Transaction_Exp_food_non_food_14 Rasun Shimul Bari","Trans_FoodNFRShimulB"],
    ["Transaction_Fin_tran_14","Trans_FinTrans"],
    ["Transaction_Loans_14","Trans_Loans"],
    ["Transaction_Sale_pur_14","Trans_SalePur"]]


destdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/IndiaVDSA_compile2/'



srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/SATIndia/Data2009/'
suff="_SATIndia_2009"
for fl in rensSATIndia2009:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")


srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/SATIndia/Data2010/'
suff="_SATIndia_2010"
for fl in rensSATIndia2010:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")


srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/SATIndia/Data2011/'
suff="_SATIndia_2011"
for fl in rensSATIndia2011:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")


srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/SATIndia/Data2012/'
suff="_SATIndia_2012"
for fl in rensSATIndia2012:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")


srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/SATIndia/Data2013/'
suff="_SATIndia_2013"
for fl in rensSATIndia2013:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")


srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/SATIndia/Data2014/'
suff="_SATIndia_2014"
for fl in rensSATIndia2014:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")


srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/EastIndia/Ei2010/'
suff="_EastIndia_2010"
for fl in rensEastIndia2010:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")

srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/EastIndia/Ei2011/'
suff="_EastIndia_2011"
for fl in rensEastIndia2011:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")

srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/EastIndia/Ei2012/'
suff="_EastIndia_2012"
for fl in rensEastIndia2012:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")
    
srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/EastIndia/Ei2013/'
suff="_EastIndia_2013"
for fl in rensEastIndia2013:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")
    
srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/EastIndia/Ei2014/'
suff="_EastIndia_2014"
for fl in rensEastIndia2014:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")
    
    
srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/Bangladesh/Bng2009/'
suff="_Bang_2009"
for fl in rensBang2009:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")
    
srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/Bangladesh/Bng2010/'
suff="_Bang_2010"
for fl in rensBang2010:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")
    
srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/Bangladesh/Bng2011/'
suff="_Bang_2011"
for fl in rensBang2011:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")
    
srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/Bangladesh/Bng2012/'
suff="_Bang_2012"
for fl in rensBang2012:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")
    
srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/Bangladesh/Bng2013/'
suff="_Bang_2013"
for fl in rensBang2013:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")
    
srcdir = r'D:/AMK/StataFiles/Data/IndiaVDSA_Data/microdata/Bangladesh/Bng2014/'
suff="_Bang_2014"
for fl in rensBang2014:
    shutil.copy(srcdir+fl[0]+".xlsx", destdir+fl[1]+suff+".xlsx")